#:root{
PRIMARY_TEXT = "#E6EDF3"
MUTED_TEXT = "#99A2AB"

BORDER_COLOR = "#222732"

BG = "#0F141B"
SEC_BG = "#13171F"

SUCCESS = "#3FB950"
SUCCESS_HOVER = "#4AC65B"
SUCCESS_PRESSED = "#339A44"

WARNING = "#D29922"
WARNING_HOVER = "#E2A62A"
WARNING_PRESSED = "#B37F1D"

DANGER = "#F85149"
DANGER_HOVER = "#FF655E"
DANGER_PRESSED = "#D8433D"

INFO = "#58A6FF"
INFO_HOVER = "#6AB3FF"
INFO_PRESSED = "#4588D1"

# Botones neutros
HOVER = "#151D31"
PRESSED = "#0F1728"

TOKENS = {
    "PRIMARY_TEXT": PRIMARY_TEXT,
    "MUTED_TEXT": MUTED_TEXT,
    "BORDER_COLOR": BORDER_COLOR,
    "HOVER": HOVER,
    "PRESSED": PRESSED,
    "BG": BG,
    "SEC_BG": SEC_BG,
    "SUCCESS": SUCCESS,
    "SUCCESS_HOVER": SUCCESS_HOVER,
    "SUCCESS_PRESSED": SUCCESS_PRESSED,
    "WARNING": WARNING,
    "WARNING_HOVER": WARNING_HOVER,
    "WARNING_PRESSED": WARNING_PRESSED,
    "DANGER": DANGER,
    "DANGER_HOVER": DANGER_HOVER,
    "DANGER_PRESSED": DANGER_PRESSED,
    "INFO": INFO,
    "INFO_HOVER": INFO_HOVER,
    "INFO_PRESSED": INFO_PRESSED,
}
#}