#:root{
PRIMARY_TEXT = "#E6EDF3"
MUTED_TEXT = "#99A2AB"

BORDER_COLOR = "#222732"

BG = "#0f141b"  #BACKGROUND
SEC_BG = "#13171f"  #SURFACE

SUCCESS = "#3FB950"
WARNING = "#D29922"
DANGER = "#F85149"
INFO = "#58A6FF"

#/*Buttons pseudo-events*/
HOVER = '#151d31'
PRESSED = '#0f1728'

TOKENS = {
    "PRIMARY_TEXT": PRIMARY_TEXT,
    "MUTED_TEXT": MUTED_TEXT,
    "BORDER_COLOR": BORDER_COLOR,
    "HOVER": HOVER,
    "PRESSED": PRESSED,
    "BG": BG,
    "SEC_BG": SEC_BG,
    "SUCCESS": SUCCESS,
    "WARNING": WARNING,
    "DANGER": DANGER,
    "INFO": INFO,
}