#:root{
PRIMARY_TEXT = "#1A2028"
MUTED_TEXT = "#5A6472"

BORDER_COLOR = "#CBD2DA"

BG = "#F0F4F8"  #BACKGROUND
SEC_BG = "#FFFFFF"  #SURFACE

SUCCESS = "#2A9E3D"
WARNING = "#B07D10"
DANGER = "#D93025"
INFO = "#0969DA"

#/*Buttons pseudo-events*/
HOVER = '#DDE4EE'
PRESSED = '#C8D0DC'

TOKENS = {
    "PRIMARY_TEXT": PRIMARY_TEXT,
    "MUTED_TEXT": MUTED_TEXT,
    "BORDER_COLOR": BORDER_COLOR,
    "HOVER": HOVER,
    "PRESSED": PRESSED,
    "BG": BG,
    "SEC_BG": SEC_BG,
    "SUCCESS": SUCCESS,
    "WARNING": WARNING,
    "DANGER": DANGER,
    "INFO": INFO,
}