#:root{
PRIMARY_TEXT = "#1A2028"
MUTED_TEXT = "#5A6472"

BORDER_COLOR = "#CBD2DA"

BG = "#F0F4F8"      # BACKGROUND
SEC_BG = "#FFFFFF"  # SURFACE

SUCCESS = "#2A9E3D"
SUCCESS_HOVER = "#33B84A"
SUCCESS_PRESSED = "#228134"

WARNING = "#B07D10"
WARNING_HOVER = "#C68C12"
WARNING_PRESSED = "#93680D"

DANGER = "#D93025"
DANGER_HOVER = "#E5483D"
DANGER_PRESSED = "#B8271E"

INFO = "#0969DA"
INFO_HOVER = "#1B7BEA"
INFO_PRESSED = "#0756B5"

# Buttons pseudo-events (botones neutros)
HOVER = "#DDE4EE"
PRESSED = "#C8D0DC"

TOKENS = {
    "PRIMARY_TEXT": PRIMARY_TEXT,
    "MUTED_TEXT": MUTED_TEXT,
    "BORDER_COLOR": BORDER_COLOR,
    "HOVER": HOVER,
    "PRESSED": PRESSED,
    "BG": BG,
    "SEC_BG": SEC_BG,
    "SUCCESS": SUCCESS,
    "SUCCESS_HOVER": SUCCESS_HOVER,
    "SUCCESS_PRESSED": SUCCESS_PRESSED,
    "WARNING": WARNING,
    "WARNING_HOVER": WARNING_HOVER,
    "WARNING_PRESSED": WARNING_PRESSED,
    "DANGER": DANGER,
    "DANGER_HOVER": DANGER_HOVER,
    "DANGER_PRESSED": DANGER_PRESSED,
    "INFO": INFO,
    "INFO_HOVER": INFO_HOVER,
    "INFO_PRESSED": INFO_PRESSED,
}

#}
